name: shop_frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  font_awesome_flutter: ^10.8.0
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  flutter_screenutil: ^5.9.0
  another_flushbar: ^1.10.29
  excel: ^4.0.6
  path_provider: ^2.1.2
  intl: ^0.20.2
  socket_io_client: ^2.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/anhbia.png
